### ISSUE TITLE
Adding more plugins

### ISSUE THREAD

**Issue by TKDev7** [re-taro/fmt#648]
Do you have plans on adding more eslint plugins? Example, eslint-plugin-playwright, eslint-plugin-node-dependencies, eslint-plugin-perfectionist etc.

**Comment by re-taro** [comment]
Hi there.
This eslint config is my personal one. So if I feel I need it. I will added

**Comment by TKDev7** [comment]
I didn’t know this was a personal one. Makes sense then.
